name: Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        symfony: ['6.2.*', '6.3.*', 6.4.*, '7.0.*', 7.1.*, 7.2.*]
        php: [8.1, 8.2, 8.3, 8.4]
        exclude:
        - php: '8.1'
          symfony: '7.0.*'
        - php: '8.1'
          symfony: '7.1.*'
        - php: '8.1'
          symfony: '7.2.*'

    name: PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-os-${{ matrix.os }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: flex

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
